// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwcx05GdI7SU40uPI7X75gMvWlvJ-8qRg',
    appId: '1:890010154373:web:381c154d01268c10cdc0ec',
    messagingSenderId: '890010154373',
    projectId: 'chatterease',
    authDomain: 'chatterease.firebaseapp.com',
    databaseURL: 'https://chatterease-default-rtdb.firebaseio.com',
    storageBucket: 'chatterease.appspot.com',
    measurementId: 'G-KTVEHY2J3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsUlrhxrxLPbLkpaA2-2rv1aVFdm-scMo',
    appId: '1:890010154373:android:f08af9590164c796cdc0ec',
    messagingSenderId: '890010154373',
    projectId: 'chatterease',
    databaseURL: 'https://chatterease-default-rtdb.firebaseio.com',
    storageBucket: 'chatterease.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg5ZvpjkJXzSgmM7GBT88KQZVXAHv_yho',
    appId: '1:890010154373:ios:aa4b7cfa86c0380fcdc0ec',
    messagingSenderId: '890010154373',
    projectId: 'chatterease',
    databaseURL: 'https://chatterease-default-rtdb.firebaseio.com',
    storageBucket: 'chatterease.appspot.com',
    iosBundleId: 'com.example.chatterEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg5ZvpjkJXzSgmM7GBT88KQZVXAHv_yho',
    appId: '1:890010154373:ios:aa4b7cfa86c0380fcdc0ec',
    messagingSenderId: '890010154373',
    projectId: 'chatterease',
    databaseURL: 'https://chatterease-default-rtdb.firebaseio.com',
    storageBucket: 'chatterease.appspot.com',
    iosBundleId: 'com.example.chatterEase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwcx05GdI7SU40uPI7X75gMvWlvJ-8qRg',
    appId: '1:890010154373:web:cb42d068086785eccdc0ec',
    messagingSenderId: '890010154373',
    projectId: 'chatterease',
    authDomain: 'chatterease.firebaseapp.com',
    databaseURL: 'https://chatterease-default-rtdb.firebaseio.com',
    storageBucket: 'chatterease.appspot.com',
    measurementId: 'G-86KYCZ59VW',
  );

}